#pragma once

const ULONG PR_CALENDAR_ENTRYID = PROP_TAG(PT_BINARY, 0x36D0);
const ULONG PR_CONTACTS_ENTRYID = PROP_TAG(PT_BINARY, 0x36D1);
const ULONG PR_JOURNAL_ENTRYID = PROP_TAG(PT_BINARY, 0x36D2);
const ULONG PR_NOTES_ENTRYID = PROP_TAG(PT_BINARY, 0x36D3);
const ULONG PR_TASKS_ENTRYID = PROP_TAG(PT_BINARY, 0x36D4);
const ULONG	PR_REMINDERS_ENTRYID = PROP_TAG(PT_BINARY, 0x36D5);
const ULONG PR_DRAFTS_ENTRYID = PROP_TAG(PT_BINARY, 0x36D7);

enum {
	DEFAULT_CALENDAR,
	DEFAULT_CONTACTS,
	DEFAULT_JOURNAL,
	DEFAULT_NOTES,
	DEFAULT_TASKS,
	DEFAULT_REMINDERS,
	DEFAULT_DRAFTS,
	DEFAULT_SENTITEMS,
	DEFAULT_OUTBOX,
	DEFAULT_DELETEDITEMS,
	DEFAULT_FINDER,
	DEFAULT_IPM_SUBTREE,
	DEFAULT_INBOX,
	DEFAULT_COMMON_VIEWS,
	NUM_DEFAULT_PROPS
};

STDMETHODIMP OpenDefaultMessageStore(LPMAPISESSION lpMAPISession, ULONG ulExplicitFlags, LPMDB * lpMDB);
STDMETHODIMP OpenDefaultFolder(ULONG ulFolder, LPMDB lpMDB, ULONG ulExplicitFlags, LPMAPIFOLDER *lpFolder);
STDMETHODIMP OpenInbox(LPMDB lpMDB, ULONG ulExplicitFlags, LPMAPIFOLDER *lpInboxFolder);
STDMETHODIMP GetFirstMessage(LPMAPIFOLDER lpFolder, ULONG ulExplicitFlags, LPMESSAGE * lppMessage);
STDMETHODIMP GetMessageNum(LPMAPIFOLDER lpFolder, ULONG ulExplicitFlags, ULONG ulMsgNum, LPMESSAGE * lppMessage);
HRESULT OpenMessageStoreGUID(
	LPMAPISESSION	lpMAPISession,
	LPCSTR lpGUID,
	LPMDB* lppMDB);
HRESULT OpenPF(LPMDB lpPFMDB, LPCTSTR lpszPFName, LPMAPIFOLDER *lppPF);
HRESULT OpenFolder(LPMDB lpMDB, LPCTSTR lpszFolderName, LPMAPIFOLDER *lppFolder);